# MITRE ATT&CK® content © 2026 The MITRE Corporation.
# This work is reproduced and distributed with the permission of The MITRE Corporation.
# See THIRD_PARTY_NOTICES.md and https://attack.mitre.org/resources/terms-of-use/
reviewed: '2026-08-27'
source_url: https://attack.mitre.org/
legal_url: https://attack.mitre.org/resources/terms-of-use/
techniques:
  T1110.003:
    name: Password Spraying
    domain: Enterprise
    tactics:
    - Credential Access
    url: https://attack.mitre.org/techniques/T1110/003/
  T1110.002:
    name: Password Cracking
    domain: Enterprise
    tactics:
    - Credential Access
    url: https://attack.mitre.org/techniques/T1110/002/
  T1078:
    name: Valid Accounts
    domain: Enterprise
    tactics:
    - Initial Access
    - Persistence
    - Privilege Escalation
    - Defense Evasion
    url: https://attack.mitre.org/techniques/T1078/
  T1552.001:
    name: Credentials In Files
    domain: Enterprise
    tactics:
    - Credential Access
    url: https://attack.mitre.org/techniques/T1552/001/
  T1566.002:
    name: Spearphishing Link
    domain: Enterprise
    tactics:
    - Initial Access
    url: https://attack.mitre.org/techniques/T1566/002/
  T1528:
    name: Steal Application Access Token
    domain: Enterprise
    tactics:
    - Credential Access
    url: https://attack.mitre.org/techniques/T1528/
  T1098.005:
    name: Device Registration
    domain: Enterprise
    tactics:
    - Persistence
    - Privilege Escalation
    url: https://attack.mitre.org/techniques/T1098/005/
  T1114.003:
    name: Email Forwarding Rule
    domain: Enterprise
    tactics:
    - Collection
    url: https://attack.mitre.org/techniques/T1114/003/
  T1539:
    name: Steal Web Session Cookie
    domain: Enterprise
    tactics:
    - Credential Access
    url: https://attack.mitre.org/techniques/T1539/
  T1195.001:
    name: Compromise Software Dependencies and Development Tools
    domain: Enterprise
    tactics:
    - Initial Access
    url: https://attack.mitre.org/techniques/T1195/001/
  T1021.004:
    name: 'Remote Services: SSH'
    domain: Enterprise
    tactics:
    - Lateral Movement
    url: https://attack.mitre.org/techniques/T1021/004/
  T1083:
    name: File and Directory Discovery
    domain: Enterprise
    tactics:
    - Discovery
    url: https://attack.mitre.org/techniques/T1083/
  T1190:
    name: Exploit Public-Facing Application
    domain: Enterprise
    tactics:
    - Initial Access
    url: https://attack.mitre.org/techniques/T1190/
  T1505:
    name: Server Software Component
    domain: Enterprise
    tactics:
    - Persistence
    url: https://attack.mitre.org/techniques/T1505/
  T1078.002:
    name: 'Valid Accounts: Domain Accounts'
    domain: Enterprise
    tactics:
    - Initial Access
    - Persistence
    - Privilege Escalation
    - Defense Evasion
    url: https://attack.mitre.org/techniques/T1078/002/
  T1187:
    name: Forced Authentication
    domain: Enterprise
    tactics:
    - Credential Access
    url: https://attack.mitre.org/techniques/T1187/
  T1557:
    name: Adversary-in-the-Middle
    domain: Enterprise
    tactics:
    - Credential Access
    - Collection
    url: https://attack.mitre.org/techniques/T1557/
  T1485:
    name: Data Destruction
    domain: Enterprise
    tactics:
    - Impact
    url: https://attack.mitre.org/techniques/T1485/
  T1486:
    name: Data Encrypted for Impact
    domain: Enterprise
    tactics:
    - Impact
    url: https://attack.mitre.org/techniques/T1486/
  T1657:
    name: Financial Theft
    domain: Enterprise
    tactics:
    - Impact
    url: https://attack.mitre.org/techniques/T1657/
  T1566.004:
    name: Spearphishing Voice
    domain: Enterprise
    tactics:
    - Initial Access
    url: https://attack.mitre.org/techniques/T1566/004/
  T1219.002:
    name: Remote Desktop Software
    domain: Enterprise
    tactics:
    - Command and Control
    url: https://attack.mitre.org/techniques/T1219/002/
